# Generated by Django 5.1 on 2024-09-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_author_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publication_data',
            new_name='publication_date',
        ),
    ]
