# Generated by Django 5.1 on 2024-09-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_remove_book_author_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
